# Generated by Django 5.1.1 on 2025-10-07 16:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('buy_or_rent', models.CharField(choices=[('rent', 'Rent'), ('buy', 'Buy')], max_length=8)),
                ('budget_max', models.IntegerField(blank=True, null=True)),
                ('beds', models.IntegerField(blank=True, null=True)),
                ('areas', models.CharField(blank=True, max_length=256)),
                ('interest_ids', models.CharField(blank=True, max_length=512)),
                ('utm_source', models.CharField(blank=True, max_length=64)),
                ('utm_campaign', models.CharField(blank=True, max_length=64)),
                ('referrer', models.URLField(blank=True)),
                ('consent_contact', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price_amount', models.IntegerField()),
                ('city', models.CharField(max_length=64)),
                ('area', models.CharField(blank=True, max_length=64)),
                ('beds', models.IntegerField(default=1)),
                ('baths', models.IntegerField(default=1)),
                ('floor_area_sqm', models.IntegerField(default=0)),
                ('parking', models.BooleanField(default=False)),
                ('hero_image', models.URLField(blank=True)),
                ('badges', models.CharField(blank=True, max_length=128)),
                ('affiliate_source', models.CharField(blank=True, max_length=64)),
                ('commissionable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
