# Generated by Django 5.1.1 on 2025-10-09 18:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('validation', 'Validation'), ('complete', 'Complete'), ('failed', 'Failed')], default='uploading', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price_amount', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=64)),
                ('area', models.CharField(blank=True, max_length=64)),
                ('beds', models.IntegerField(blank=True, null=True)),
                ('baths', models.IntegerField(blank=True, null=True)),
                ('hero_image', models.ImageField(blank=True, upload_to='property_uploads/')),
                ('ai_validation_result', models.JSONField(blank=True, default=dict)),
                ('missing_fields', models.JSONField(blank=True, default=list)),
                ('validation_chat_history', models.JSONField(blank=True, default=list)),
                ('consolidated_information', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
