# Generated by Django 5.1.2 on 2025-10-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_propertyupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyupload',
            name='hero_image',
            field=models.URLField(blank=True),
        ),
    ]
