# Generated by Django 5.2.7 on 2025-10-22 10:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_propertyupload_hero_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.URLField(blank=True)),
                ('brand_primary_color', models.CharField(default='#3B82F6', help_text='Hex color code', max_length=7)),
                ('brand_secondary_color', models.CharField(default='#1E40AF', help_text='Hex color code', max_length=7)),
                ('brand_tone', models.CharField(default='professional', help_text='Brand personality tone', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='autoresponder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='webhook_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='webhook_last_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='webhook_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='estimate',
            field=models.IntegerField(blank=True, help_text='Market value estimate', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='last_updated',
            field=models.DateTimeField(blank=True, help_text='Last enrichment update', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='narrative',
            field=models.TextField(blank=True, help_text='AI-generated property analysis'),
        ),
        migrations.AddField(
            model_name='property',
            name='neighborhood_avg',
            field=models.IntegerField(blank=True, help_text='Neighborhood average price', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='source',
            field=models.CharField(blank=True, help_text='Data source (rentcast, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.company'),
        ),
        migrations.AddField(
            model_name='property',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.company'),
        ),
        migrations.AddField(
            model_name='propertyupload',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.company'),
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutboxMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('retry', 'Retry')], default='pending', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('correlation_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
