# Generated by Django 5.1.2 on 2025-10-29 10:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_campaign_plan_propertyembedding_subscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('lease_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('leased', 'Leased'), ('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('retried', 'Retried')], max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='myApp.jobtask')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LeadMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('chat', 'Chat'), ('facebook', 'Facebook Messenger'), ('instagram', 'Instagram Direct'), ('email', 'Email'), ('webform', 'Web Form')], max_length=20)),
                ('external_thread_id', models.CharField(max_length=255)),
                ('external_msg_id', models.CharField(blank=True, max_length=255)),
                ('sender_type', models.CharField(choices=[('human', 'Human'), ('bot', 'Bot')], default='human', max_length=10)),
                ('text', models.TextField()),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.lead')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadPropertyLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confidence', models.FloatField(default=0.0, help_text='Confidence score 0.0-1.0')),
                ('evidence', models.TextField(blank=True, help_text='Reason for linking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.lead')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.organization')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.property')),
            ],
            options={
                'ordering': ['-confidence', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('facebook', 'Facebook Messenger'), ('instagram', 'Instagram Direct'), ('email_inbound', 'Inbound Email'), ('chat', 'Chat')], max_length=20)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('not_connected', 'Not Connected'), ('error', 'Error'), ('pending', 'Pending')], default='not_connected', max_length=20)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.organization')),
            ],
            options={
                'ordering': ['channel'],
                'unique_together': {('organization', 'channel')},
            },
        ),
        migrations.AddIndex(
            model_name='jobtask',
            index=models.Index(fields=['status', 'next_attempt_at'], name='myApp_jobta_status_3a7601_idx'),
        ),
        migrations.AddIndex(
            model_name='jobtask',
            index=models.Index(fields=['organization', 'created_at'], name='myApp_jobta_organiz_9e23da_idx'),
        ),
        migrations.AddIndex(
            model_name='jobtask',
            index=models.Index(fields=['lease_id'], name='myApp_jobta_lease_i_0e723b_idx'),
        ),
        migrations.AddIndex(
            model_name='leadmessage',
            index=models.Index(fields=['organization', 'created_at'], name='myApp_leadm_organiz_5ba367_idx'),
        ),
        migrations.AddIndex(
            model_name='leadmessage',
            index=models.Index(fields=['organization', 'external_thread_id', 'created_at'], name='myApp_leadm_organiz_b72c43_idx'),
        ),
        migrations.AddIndex(
            model_name='leadmessage',
            index=models.Index(fields=['channel', 'created_at'], name='myApp_leadm_channel_449504_idx'),
        ),
        migrations.AddIndex(
            model_name='leadpropertylink',
            index=models.Index(fields=['lead', 'property'], name='myApp_leadp_lead_id_fa7992_idx'),
        ),
        migrations.AddIndex(
            model_name='leadpropertylink',
            index=models.Index(fields=['organization', 'confidence'], name='myApp_leadp_organiz_5667e5_idx'),
        ),
    ]
