# Generated by Django 5.1.2 on 2025-10-29 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_emailaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagelog',
            options={'ordering': ['-sent_at']},
        ),
        migrations.RemoveConstraint(
            model_name='emailaccount',
            name='unique_org_email',
        ),
        migrations.RemoveIndex(
            model_name='emailaccount',
            name='myapp_emaila_organiz_2b8a0b_idx',
        ),
        migrations.RemoveIndex(
            model_name='emailaccount',
            name='myapp_emaila_organiz_4a8b1c_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='myApp_lead_organiz_97c82b_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='myApp_lead_organiz_c0ba2c_idx',
        ),
        migrations.RemoveIndex(
            model_name='messagelog',
            name='myApp_messa_organiz_a6fa24_idx',
        ),
        migrations.RemoveIndex(
            model_name='messagelog',
            name='myApp_messa_lead_id_e38d1f_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='myApp_prope_organiz_d917ce_idx',
        ),
        migrations.RemoveField(
            model_name='campaignstep',
            name='offset_days',
        ),
        # Moved AlterUniqueTogether after company field is added
        migrations.RemoveField(
            model_name='lead',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='conversation_id',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='source',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='status',
        ),
        migrations.RemoveField(
            model_name='messagelog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='messagelog',
            name='provider_message_id',
        ),
        migrations.RemoveField(
            model_name='property',
            name='is_active',
        ),
        migrations.AddField(
            model_name='campaign',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='myApp.company'),
        ),
        migrations.AddField(
            model_name='campaignstep',
            name='delay_hours',
            field=models.IntegerField(default=0, help_text='Hours to wait after previous step (0 for immediate)'),
        ),
        migrations.AddField(
            model_name='campaignstep',
            name='name',
            field=models.CharField(blank=True, help_text="Step name (e.g., 'Welcome Email')", max_length=255),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to='myApp.company'),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_logs', to='myApp.company'),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='email_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.emailaccount'),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='message_id',
            field=models.CharField(blank=True, help_text='Provider message ID', max_length=255),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='provider',
            field=models.CharField(default='gmail', help_text='Email provider used', max_length=20),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.organization'),
        ),
        migrations.AlterField(
            model_name='campaignstep',
            name='body_template',
            field=models.TextField(help_text='Email body template. Use {{ lead.name }}, {{ company.name }} for variables.'),
        ),
        migrations.AlterField(
            model_name='campaignstep',
            name='order',
            field=models.IntegerField(default=0, help_text='Order in sequence'),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Primary email account for company'),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_logs', to='myApp.campaign'),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='campaign_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_logs', to='myApp.campaignstep'),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error details if failed'),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_logs', to='myApp.lead'),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.organization'),
        ),
        migrations.AddIndex(
            model_name='emailaccount',
            index=models.Index(fields=['company', 'is_active'], name='myApp_email_company_23accb_idx'),
        ),
        migrations.AddIndex(
            model_name='emailaccount',
            index=models.Index(fields=['company', 'is_primary'], name='myApp_email_company_2d940b_idx'),
        ),
        migrations.RemoveField(
            model_name='emailaccount',
            name='organization',
        ),
        migrations.AlterUniqueTogether(
            name='emailaccount',
            unique_together={('company', 'email_address')},
        ),
    ]
